services:
  mysql:
    image: mysql:latest
    container_name: niceplanet_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: niceplanet
    ports:
      - "3306:3306"
    volumes:
      - ./testeFullStack.sql:/docker-entrypoint-initdb.d/testeFullStack.sql:ro
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql_data:
    driver: local